juanwolf_fr/api/urls.py
from rest_framework import routers
from api import views

# Creating a default router, to learn more about read :
# http://www.django-rest-framework.org/api-guide/routers/#defaultrouter
router = routers.DefaultRouter()

router.register(r'posts', viewset=views.PostViewSet)
router.register(r'categories', viewset=views.CategoryViewSet)
router.register(r'tags', viewset=views.TagViewSet)

urlpatterns = router.urls

juanwolf_fr/blogengine/urls.py
from django.conf.urls import include, url
from django.contrib.sitemaps.views import sitemap

from blogengine import views, models

app_name = 'blog'

sitemaps = {
    'blog': models.BlogSitemap
}

urlpatterns = [

    # Post RSS feed
    url(r'^feeds/posts/$', views.PostsFeed(), name='rss'),

    # Summernote
    url(r'^summernote/', include('django_summernote.urls')),

    url(
        r'^sitemap\.xml$',
        sitemap,
        {
            'sitemaps': sitemaps,
            'template_name': 'custom_sitemap.html'
        },
        name='django.contrib.sitemaps.views.sitemap',
    ),

    # Index
    url(
        r'^(?P<page>\d+)?/?$',
        views.PostListView.as_view(model=models.Post, paginate_by=5),
        name='index'
    ),
    # Tags
    url(
        r'^tag/(?P<slug>[a-zA-Z0-9-]+)/?$',
        views.TagDetailView.as_view(model=models.Tag),
        name='tag-detail'
    ),
    # Individual posts
    url(
        r'^(?P<category__slug>[a-zA-Z0-9\-]+)/(?P<slug>[a-zA-Z0-9-]+)/?$',
        views.PostDetailView.as_view(model=models.Post),
        name='post-detail'
    ),
    url(
        r'^(?P<pub_date__year>\d{4})/(?P<pub_date__month>\d{1,2})/(?P<slug>[a-zA-Z0-9-]+)/?$',  # noqa
        views.RedirectPostDetailView.as_view()
    ),
    # Categories
    url(
        r'^(?P<slug>[a-zA-Z0-9-]+)/?$',
        views.CategoryDetailView.as_view(paginate_by=5, model=models.Category),
        name='category-detail'
    ),
]

juanwolf_fr/juanwolf_fr/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

from rest_framework_swagger.views import get_swagger_view


admin.autodiscover()

schema_view = get_swagger_view(title='Pastebin API')

urlpatterns = [
    # Summernote
    url(r'^summernote/', include('django_summernote.urls')),

    # Internationalization
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # Admin
    url(r'^admin/', include(admin.site.urls)),
    # API
    url(r'^api/docs/', schema_view),
    url(r'^api/', include('api.urls')),
    # Blog
    url(r'', include('blogengine.urls', namespace="blog")),
]

handler404 = 'blogengine.views.page_not_found_view'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(url(r'^__debug__/', include(debug_toolbar.urls)))

juanwolf_fr/blogengine/models.py
from datetime import datetime

from django.contrib.sitemaps import Sitemap
from django.db import models
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _

from juanwolf_fr.settings import MEDIA_URL


def upload_path(self, filename):
    import time
    return '%s_%s' % (time.strftime("%Y%m%d_%H%M%S"), filename)


class Tag(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    slug = models.SlugField(max_length=40, unique=True, blank=True, null=True)

    def save(self):
        if not self.slug:
            self.slug = slugify(str(self.name))
        super(Tag, self).save()

    def get_absolute_url(self):
        return "/tag/%s/" % (self.slug)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    slug = models.SlugField(max_length=40, unique=True, blank=True, null=True)

    def save(self):
        if not self.slug:
            self.slug = slugify(str(self.name))
        super(Category, self).save()

    def get_absolute_url(self):
        url = "/%s/" % self.slug
        return url

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = _('categories')


class Post(models.Model):
    pub_date = models.DateTimeField(default=datetime.now)
    image = models.ImageField(upload_to=upload_path, blank=True, null=True)
    keywords = models.TextField(blank=True, null=True)
    category = models.ForeignKey(Category, default="")
    tags = models.ManyToManyField(Tag, blank=True)
    title = models.CharField(max_length=200, default="")
    text = models.TextField(default="")
    slug = models.SlugField(max_length=50, unique=True)

    def get_absolute_url(self):
        return "/%s/%s/" % (self.category.slug, self.slug)

    def get_absolute_image_url(self):
        return '/%s%s' % (MEDIA_URL, self.image.name)

    def get_introduction(self):
        # Find first paragraph
        all_paragraph = self.text.split("</p>")
        # Delete p tag
        paragraph_content = all_paragraph[0].replace("<p>", "")
        return paragraph_content

    def get_text_content(self):
        # Find first paragraph
        introduction = self.get_introduction()
        introduction_with_tag = "<p>%s</p>" % introduction

        post_content = self.text[len(introduction_with_tag):]
        return post_content

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-pub_date"]
        index_together = [['pub_date']]


class BlogSitemap(Sitemap):
    changefreq = "daily"
    priority = 0.5
    i18n = True
    protocol = "https"

    def items(self):
        return Post.objects.all()

    def lastmod(self, obj):
        return obj.pub_date

juanwolf_fr/blogengine/forms.py
__author__ = 'juanwolf'

juanwolf_fr/blogengine/views.py
from django.contrib.syndication.views import Feed

from django.core.urlresolvers import reverse_lazy
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.template import RequestContext
from django.utils import translation
from django.utils.translation import ugettext as _
from django.views.generic import DetailView, ListView, RedirectView

from blogengine import models


class CategoryDetailView(ListView, DetailView):
    template_name = "category_detail.html"
    context_object_name = "post_list"
    translation = None
    category = None

    def get_queryset(self):
        slug = self.kwargs['slug']
        if not self.translation:
            try:
                # Try to get the category if not raise an exception
                self.category = models.Category.objects.get(slug_en=slug)
                translation.activate("en")
                self.translation = 'en'
            except models.Category.DoesNotExist:
                pass
            else:
                return self.category.post_set.all().prefetch_related(
                        'tags').select_related('category')

            try:
                # Try to get the the category if not raise an exception
                self.category = models.Category.objects.get(slug_fr=slug)
                translation.activate("fr")
                self.translation = 'fr'
            except models.Category.DoesNotExist:
                raise Http404
            else:
                return models.Post.objects.filter(
                        category__slug_fr=slug
                    ).prefetch_related('tags').select_related('category')
        else:
            translation.activate(self.translation)
            return models.Post.objects.filter(
                category__slug=slug
            ).prefetch_related('tags').select_related('category')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        # Add in a querySet the category
        self.object = self.get_queryset()
        context = super(CategoryDetailView, self).get_context_data(**kwargs)
        slug = self.kwargs['slug']
        translation.activate(self.translation)
        if self.category:
            context['category'] = self.category
        else:
            context['category'] = models.Category.objects.get(slug=slug)
        return context


class CategoryListView(ListView):
    template_name = "category_list.html"
    context_object_name = "category_list"

    def get_queryset(self):
        return models.Category.objects.all().prefetch_related('post_set')


class TagDetailView(ListView):
    template_name = "tag_detail.html"
    model = models.Tag

    def get_queryset(self):
        slug = self.kwargs['slug']
        try:
            tag = models.Tag.objects.get(slug_fr=slug)
        except models.Tag.DoesNotExist:
            try:
                tag = models.Tag.objects.get(slug_en=slug)
            except models.Tag.DoesNotExist:
                raise Http404

        return tag.post_set.all().select_related(
            'category').prefetch_related('tags')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        # Add in a querySet the category
        context = super(TagDetailView, self).get_context_data(**kwargs)
        slug = self.kwargs['slug']
        try:
            context['tag'] = models.Tag.objects.get(slug_fr=slug)
            translation.activate('fr')
        except models.Tag.DoesNotExist:
            try:
                context['tag'] = models.Tag.objects.get(slug_en=slug)
                translation.activate('en')
            except models.Tag.DoesNotExist:
                raise Http404

        return context


class PostListView(ListView):
    template_name = "post_list.html"
    context_object_name = "post_list"

    def get_queryset(self):
        return models.Post.objects.all().select_related(
            'category').prefetch_related('tags')


class PostDetailView(DetailView):
    template_name = "post_detail.html"
    context_object_name = "post"
    # form_class = CommentsForm

    def get_queryset(self):
        slug = self.kwargs['slug']
        post = models.Post.objects.filter(slug_en=slug).select_related(
            'category').prefetch_related('tags')
        if post.exists():
            translation.activate("en")
            return post
        post = models.Post.objects.filter(slug_fr=slug)
        if post.exists():
            translation.activate("fr")
            return post.prefetch_related('tags').select_related(
                'category').prefetch_related('tags')
        raise Http404

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        # Add in a querySet the category
        context = super(PostDetailView, self).get_context_data(**kwargs)
        post = context['post']

        try:
            next_post = post.get_next_by_pub_date()
            context['next_post'] = next_post
            context['has_next_post'] = True
        except models.Post.DoesNotExist:
            context['has_next_post'] = False

        try:
            previous_post = post.get_previous_by_pub_date()
            context['has_previous_post'] = True
            context['previous_post'] = previous_post
        except models.Post.DoesNotExist:
            context['has_previous_post'] = False

        return context


class RedirectPostDetailView(RedirectView):
    permanent = True
    query_string = False
    pattern_name = 'post-detail'

    def get_redirect_url(self, *args, **kwargs):
        post = get_object_or_404(models.Post, slug=kwargs['slug'])
        kwargs['category__slug'] = post.category.slug
        return reverse_lazy(
            'blog:post-detail', args=[post.category.slug, kwargs['slug']])


class PostsFeed(Feed):
    title = _("RSS feed - posts")
    link = "feeds/posts/"
    description = _("RSS feed - blog posts")

    def items(self):
        return models.Post.objects.order_by('-pub_date')

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.text


def page_not_found_view(request, template_name='page_not_found.html'):
    context = RequestContext(
        request,
        {"categories": models.Category.objects.all()}
    )
    response = render(request, template_name, context.flatten())
    response.status_code = 404
    return response

juanwolf_fr/blogengine/templates/category_detail.html
{% extends "includes/base.html" %}
   {% block language-redirection %}
        {% load i18n %}
    {% if LANGUAGE_CODE == "en" %}
        {% language 'fr' %}
        value={% url 'blog:category-detail' category.slug %}
        {% endlanguage %}
    {% else %}
        {% language 'en' %}
        value={% url 'blog:category-detail' category.slug %}
        {%  endlanguage %}
    {% endif %}
    {% endblock %}
   {% block  content %}
   {% load i18n %}
   <h1> {{ category.name }} </h1>
   <p class="description category-desc"> {{ category.description}}</p>
   {% for post in post_list %}
        {% include "post_preview_template.html" %}
   {% empty %}
        <p>{% trans "There's no post in this category for the moment" %} =(
            {% trans "All our engineers are working on it. We'll fix this problem soon." %}
        </p>
   {% endfor %}

   {% endblock %}

juanwolf_fr/blogengine/templates/category_list.html
{% load i18n %}
<li>
  <a id="link-home-blog" href="{% url 'blog:index' %}">{% trans 'Home' %}</a>
</li>
{% for category in categories %}
<li>
  <a id="category-{{category.slug_en}}" href="{% url 'blog:category-detail' category.slug %}">
        {{ category.name }}
    </a>
    </li>
{% endfor %}
<li>
  <a id="link-rss" href="{% url 'blog:rss' %}">RSS</a>
</li>

juanwolf_fr/blogengine/templates/create_comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

juanwolf_fr/blogengine/templates/custom_sitemap.html
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xhtml="http://www.w3.org/1999/xhtml">
{% load i18n %}
{% for url in urlset %}

  <url>
    <loc>{{ url.location }}</loc>

    {% if url.lastmod %}<lastmod>{{ url.lastmod|date:"Y-m-d" }}</lastmod>{% endif %}
    {% if url.changefreq %}<changefreq>{{ url.changefreq }}</changefreq>{% endif %}
    {% if url.priority %}<priority>{{ url.priority }}</priority>{% endif %}
    {% language 'fr'%}
    <xhtml:link
        rel="alternate"
        hreflang="fr"
        href="https://blog.juanwolf.fr{% url 'blog:post-detail' url.item.category.slug url.item.slug %}"
        />
    {% endlanguage %}
    {% language 'en'%}
    <xhtml:link
        rel="alternate"
        hreflang="en"
        href="https://blog.juanwolf.fr{% url 'blog:post-detail' url.item.category.slug url.item.slug %}"
        />
    {% endlanguage %}
  </url>


{% endfor %}
</urlset>

juanwolf_fr/blogengine/templates/page_not_found.html
{% extends "includes/base.html" %}
{% block content %}
     {% load i18n %}
     {% load staticfiles %}
    <p id="not-found-title"> {% trans 'HEY, WHAT ARE YOU DOING HERE ?!!' %}</p>
        <div id="image-not-found">
            <img src='{% static "img/panda-invasion-2.png" %}' alt="{%  trans 'My pandas are watching you' %}" />
        </div>
    <p id="not-found-text">
        {% trans "My pandas saw you going to a bad URL, it's ok for this time but try not to do it again." %}
    </p>
{% endblock %}

juanwolf_fr/blogengine/templates/post_detail.html
{% extends "includes/base.html" %}
{% load i18n %}
{% if post.keywords %}
    {% block head_block %}
        {% if LANGUAGE_CODE == "fr" %}
        <meta name="description" content="{{ post.get_introduction }}">
        {% if post.keywords %}
        <meta name="keywords" content="{{ post.keywords  }}" />
        {% endif %}
        <meta name="author" content="Jean-Loup Adde"/>
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:site" content="@juan__wolf" />
        <meta name="twitter:creator" content="@juan__wolf" />
        <meta name="twitter:title" content="{{ post.title }} - blog.juanwolf.fr" />
        <meta name="twitter:description" content="{{ post.get_introduction }}" />
        {% if post.image %}
        <meta name="twitter:image" content="{{ post.get_absolute_image_url }}" />
        {% endif %}
        <meta name="twitter:url" content="{{ current_path }}" />
        <meta name="og:url" content="{{ current_path }}" />
        <meta name="og:title" content="{{ post.title }} - blog.juanwolf.fr"/>
            {% if post.image %}
        <meta name="og:image" content="{{ post.get_absolute_image_url }}"/>
                {% endif %}
        <meta name="og:description" content="{{ post.get_introduction }}" />
        <meta name="og:locale" content="fr_FR">
        <meta name="og:author" content="Jean-Loup Adde" />
        <meta name="og:type" content="article" />
        {% else %}
        <meta name="description" content="{{ post.get_introduction }}">
        {% if post.keywords %}
        <meta name="keywords" content="{{ post.keywords  }}" />
        {% endif %}
        <meta name="author" content="Jean-Loup Adde"/>
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:site" content="@juan__wolf" />
        <meta name="twitter:creator" content="@juan__wolf" />
        <meta name="twitter:title" content="{{ post.title }} - blog.juanwolf.fr" />
        <meta name="twitter:description" content="{{ post.get_introduction }}" />
        {% if post.image %}
        <meta name="twitter:image" content="{{ post.get_absolute_image_url }}" />
        {% endif %}
        <meta name="twitter:url" content="{{ current_path }}" />
        <meta name="og:url" content="{{ current_path }}" />
        <meta name="og:title" content="{{ post.title }} - blog.juanwolf.fr"/>
        {% if post.image %}
        <meta name="og:image" content="{{ post.get_absolute_image_url }}"/>
        {% endif %}
        <meta name="og:description" content="{{ post.get_introduction }}" />
        <meta name="og:locale" content="en_GB">
        <meta name="og:author" content="Jean-Loup Adde" />
        <meta name="og:type" content="article" />
        {% endif %}
    {% endblock %}
{% endif %}


{% block title %} {{ post.title }} -  {% endblock %}
{% block language-redirection %}
    {% if LANGUAGE_CODE == "en" %}
        {% language 'fr' %}
        value="{% url 'blog:post-detail' post.category.slug post.slug %}"
        {% endlanguage %}
    {% else %}
        {% language 'en' %}
        value="{% url 'blog:post-detail' post.category.slug post.slug %}"
        {%  endlanguage %}
    {% endif %}
{% endblock %}

{% block content %}
    {% include "includes/post_template.html" %}
{% endblock %}

juanwolf_fr/blogengine/templates/post_list.html
{% extends "includes/base.html" %}
    {% block content %}
        {% load i18n %}
        {% for post in post_list %}
        {% include 'post_preview_template.html' %}
        {% empty %}
            <p> {% trans "There's no post for the moment" %}  =(
                {% trans "All our engineers are working on it. We'll fix this problem soon." %}
            </p>
        {% endfor %}
        <nav class="pagination">
        {% if page_obj.has_previous %}
            <a id="previous-page" href="/{{ page_obj.previous_page_number }}/">
                &lsaquo; {% trans 'Newer posts' %}
            </a>
        {% endif %}
        {% if page_obj.has_next %}
            <a id="next-page" href="/{{ page_obj.next_page_number }}/">
                {% trans 'Older posts' %} &rsaquo;
            </a>
        {% endif %}
        </nav>
    {% endblock %}

juanwolf_fr/blogengine/templates/post_preview_template.html
{%extends "includes/base_post.html" %}
    {% block post_content %}
    {% if post.image %}
    <div class="post-content-preview-with-img">
        {% load i18n %}
        <p class="post-content-preview-text">{{ post.get_introduction | safe | truncatewords_html:70 }}</p>
        <img class="post-content-preview-img" src="{{  MEDIA_URL }}{{ post.image.name }}" alt="{% trans "Preview Image for the article : " %} {{ post.title }}"/>
    </div>
    {% else %}
    <div class="post-content-preview">
        <p class="post-content-preview-text">{{ post.get_introduction | safe | truncatewords_html:100 }}</p>
    </div>
    {% endif %}
    {% load i18n %}
    <a href="{% url "blog:post-detail" post.category.slug post.slug %}">{% trans "Read this post" %} &rsaquo;</a>
    {% endblock %}

juanwolf_fr/blogengine/templates/tag_detail.html
{% extends "includes/base.html" %}
{% block language-redirection %}
    {% load i18n %}
    {% if LANGUAGE_CODE == "en" %}
        {% language 'fr' %}
            value="{% url "blog:tag-detail" tag.slug %}"
        {% endlanguage %}
    {% else %}
        {% language 'en' %}
            value="{% url "blog:tag-detail" tag.slug %}"
        {%  endlanguage %}
    {% endif %}
{% endblock %}
{% block content %}
    {% load i18n %}
    <h1>{{ tag.name }}</h1>
    <p>{{ tag.description }}</p>
    {% for post in object_list %}
        {% include "post_preview_template.html" %}
    {% empty %}
        <p> {% trans "There's no post for this tag for the moment" %} =(
            {% trans "All our engineers are working on it. We'll fix this problem soon." %}
        </p>
    {% endfor %}
{% endblock %}